inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'spec/fixtures/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'bin/**/*'
    - 'bundler_stubs/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'config/environments/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 8

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
