# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.4.0'

gem 'concerning_services', path: 'vendor/gems/concerning_services-0.0.24'
gem 'showoff_api', path: 'vendor/gems/showoff_api-0.0.7'
gem 'showoff_current_api_user', path: 'vendor/gems/showoff_current_api_user-0.0.1'
gem 'showoff_payments', path: 'vendor/gems/showoff_payments-1.3.8'
gem 'showoff_response_codes', path: 'vendor/gems/showoff_response_codes-0.0.2'
gem 'showoff_serializable', path: 'vendor/gems/showoff_serializable-0.0.3'
gem 'showoff_sns', path: 'vendor/gems/showoff_sns-1.0.3'

gem 'actioncable'
gem 'active_interaction', '~> 3.6'
gem 'active_model_serializers'
gem 'activerecord-postgis-adapter'
gem 'apipie-rails'
gem 'attr_encrypted', '~> 3.0.0'
gem 'aws-sdk', '< 3.0'
gem 'aws-sdk-core'
gem 'blazer'
gem 'bootstrap-sass'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.37'
gem 'bourbon', '5.0.0.beta.5'
gem 'browser'
gem 'business_time'
gem 'cancancan'
gem 'chartkick'
gem 'coffee-rails'
gem 'cookies_eu'
gem 'countries'
gem 'country_select'
gem 'data-confirm-modal'
gem 'devise'
gem 'devise-async', github: 'mhfs/devise-async', branch: 'devise-4.x'
gem 'devise_invitable'
gem 'doorkeeper'
gem 'doorkeeper-grants_assertion', git: 'https://github.com/uniiverse/doorkeeper-grants_assertion.git'
gem 'dotiw'
gem 'email_address'
gem 'excon', '~> 0.62.0'
gem 'figaro'
gem 'filterrific'
gem 'flutie'
gem 'font-awesome-sass'
gem 'foreman'
gem 'fullcalendar-rails'
gem 'geocoder'
gem 'globalize', '~> 5.0.0'
gem 'globalize-accessors'
gem 'gmaps4rails'
gem 'google_places'
gem 'groupdate'
gem 'high_voltage'
gem 'hirefire-resource'
gem 'honeybadger'
gem 'http_accept_language'
gem 'icheck-rails'
gem 'imgkit'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jwt', '~> 2.1.0'
gem 'koala'
gem 'mailchimp-api', require: 'mailchimp'
gem 'momentjs-rails', '>= 2.9.0'
gem 'money'
gem 'money-currencylayer-bank'
gem 'money-rails'
gem 'morrisjs-rails'
gem 'neat', '~> 1.7.0'
gem 'nested_form'
gem 'newrelic_rpm', '>= 3.9.8'
gem 'nokogiri', '~> 1.10.10'
gem 'normalize-rails', '~> 3.0.0'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'paper_trail'
gem 'paperclip'
gem 'paperclip-av-transcoder'
gem 'pg'
gem 'premailer-rails'
gem 'puma'
gem 'puma_worker_killer'
gem 'pusher-chatkit-server'
gem 'rack-attack'
gem 'rack-canonical-host'
gem 'rails', '~> 4.2.0'
gem 'raphaeljs-rails'
gem 'recipient_interceptor'
gem 'remotipart', '~> 1.2'
gem 'request_store'
gem 'responders', '~> 2.0'
gem 'rest-client'
gem 'rgeo-geojson'
gem 'rolify'
gem 'sass-rails', '~> 5.0'
gem 'select2-rails'
gem 'sidekiq', '~> 4.2.10'
gem 'sidekiq-statistic'
gem 'sidekiq-status'
gem 'simple_form'
gem 'sinatra', require: false
gem 'slim'
gem 'slim-rails'
gem 'sprockets', '>= 3.0.0'
gem 'sprockets-es6'
gem 'stripe', '~> 1.43'
gem 'switchery-rails'
gem 'title'
gem 'twilio-ruby'
gem 'twitter-text'
gem 'twitter-typeahead-rails'
gem 'uglifier'
gem 'underscore-rails'
gem 'where-or'
gem 'wicked_pdf'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'wkhtmltoimage-binary'
gem 'wkhtmltopdf-binary'
gem 'wkhtmltopdf-heroku'
gem 'validate_url'
gem 'rack-cors', require: 'rack/cors'

group :development, :test do
  gem 'dotenv-rails'
end

group :development do
  gem 'letter_opener'
  gem 'letter_opener_web', '~> 1.2.0'
  gem 'quiet_assets'
  gem 'solargraph'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'web-console'
end

group :development do
  gem 'awesome_print'
  gem 'bullet'
  gem 'bundler-audit', '>= 0.5.0', require: false
  gem 'factory_girl_rails'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.4.0'
  gem 'rubocop', '~> 0.62.0', require: false
  gem 'thin'
end

group :development, :staging do
  gem 'rack-mini-profiler', require: false
  gem 'rails-erd'
end

group :staging, :production do
  gem 'rack-timeout'
  gem 'rails_12factor'
  gem 'rails_autoscale_agent'
  gem 'rails_stdout_logging'
end
